using System.Collections.Generic;
using NuciText.Grammar.Rules;

namespace NuciText.Grammar.Romanian.Rules;

/// <summary>
/// Adds Romanian diacritics and other high-confidence orthographic fixes.
/// </summary>
internal sealed class RomanianDiacriticsRule : PatternReplacementRuleBase
{
    static readonly IReadOnlyList<RegexReplacement> replacements = CreateReplacements();

    /// <inheritdoc/>
    public override string Id => "romanian-diacritics";

    /// <inheritdoc/>
    public override string Description => "Adds Romanian diacritics and normalises common orthographic forms.";

    /// <inheritdoc/>
    protected override string DoApply(string text)
        => ApplyWordReplacements(text, replacements);

    static IReadOnlyList<RegexReplacement> CreateReplacements()
    {
        List<RegexReplacement> values =
        [
            new("([Aa])[sș](a|chi[ae]|eza(i|m|re|rea|t|te|tele)|tept(a|ai|are|area|at|at[aă]|au)*|tern(e|ut(u[l]*|ului|uri(le|lor)*)*)*)", "$1ș$2"),
            new("([Aa])t[aâq](rna[a-z][a-z]*|t[a-z]*)", "$1tâ$2"),
            new("([Cc])[aâ](cat|n(d|tec)|rp(e|it[e]*)|t(e|or))", "$1â$2"),
            new("([Cc])[aă](dea|lare|r(a|a(re(a)*|t(e)*)|ui(a)*)|zut(e)*)", "$1ă$2"),
            new("([Gg])[aă](([st]i)(m|t[e]*))", "$1ă$2"),
            new("([Mm])[aâ](dr(e|ele|elor|i|ie|iei|ii|u|ul|ului)|ec(a|i|ile|ilor)|in(e|i|ile|ilor)|na[a]*|nc(ar(e|ea)|at(e|ele|elor)*)|ni(a|e|ei))", "$1â$2"),
            new("([Pp])l[aă](cut[e]*|t(esc|it))", "$1lă$2"),
            new("([Aa](ib|lea[r]*g|rtificial)|[Cc]ad|[Dd]up|[Ll]eag|[Mm]|[Nn]eag|[Pp]leac)[aă]", "$1ă"),
            new("([Cc]ules|[Mm]ers|[Pp]us)[aă]i", "$1ăi"),
            new("([Ee]limin|[Ff]um|[Ll]eg|[Pp]rob|[Uu](mbl|r[cm]))[aă]m", "$1ăm"),
            new("([Ss]eam|[Zz]drav)[aă]n[aă]", "$1ănă"),
            new("([Bb]l|[Cc]ur|[Gg]|[Mm]erg|[Oo]ric)[aq]nd", "$1ând"),
            new("([Cc]re|[Dd]ovede|[Ff]ere|[Ll](eneve|uce)|[Mm](inere|unce)|[Oo]pre|[Tt]rebui|[Uu]r|[Vv]orbe)asc[aă]", "$1ască"),
            new("([Ii]ntr|[Ll](eg|ua)|[Mm]ut|[Pp]lec|[Tt](ermin|r)|[Uu]it)[aq]*[sș]i", "$1ași"),
            new("([Cc]cules|[Mm]ers)[aăq][sș]i", "$1ăși"),
            new("([Aa]di|[Dd]a|[Ff](a|ri)|[Jj]oa|[Oo]lea|[Pp]l[e]*a)c[aă]", "$1că"),
            new("([Cc]hip|[Oo]ach|[Ll]en|[Mm]ol)e[sș](e|ele|elor|i|ii|ilor|im|it|ite)?", "$1eș$2"),
            new("([Aa]lea[r]*|[Cc]ulea|[Dd]istru)g[aă]", "$1gă"),
            new("([Cc]cul)e[sș]i", "$1eși"),
            new("([Cc]it|[Oo]pr|[Pp](orn|rim)|[Vv]en)i[sș]i", "$1iși"),
            new("([Cc]((e)*a|oboa)|[Oo]moa|[Pp]ia|[Ss](a|ea))r[aă]", "$1ră"),
            new("([Tt]oa)rc[aă]", "$1rcă"),
            new("([Tt]oa)rs[aă]", "$1rsă"),
            new("([Aa](lea|pu)|[Cc]ulea|[Dd]u|[Jj]oa|[Pp][au])s[aă]", "$1să"),
            new("([Aa]linta|[Cc]ealal|[Dd]ezvol|[Ff]ura|[Ii]ntra|[Mm]uta|[Pp]oa|[Rr]oa|[Tt](ermina|oa))t[aă]", "$1tă"),
            new("([Dd]imine[a]*|[Ff]or|[Nn]ea|[Tt]or|[Vv](erdea|ia|oin))[tț](a|e|ei|ele|elor)", "$1ț$2"),
            new("([Aa](dministra|ltera|pari|utocra|vu)|[Bb]og[aă]|[Cc]o(ntribu|ta)|[Dd](emocra|iscre)|[Ee]mo|[Ll]ega|[Pp](oli|rotec)|[Tt]ranzac)[tț]i(a|e|ei|i|ile|ilor|lor|ona|onat|onate|onatele|onatelor)?", "$1ți$2"),
            new("al(a|alalt|ora)", "ăl$1"),
            new("([Aa])lba[sș]tri(i|lor)*", "$1lbaștri$2"),
            new("([Aa])l[tț]i(i)*", "$1lți$2"),
            new("([Aa])r[ae][tț]i", "$1răți"),
            new("([Aa])ve[tț]i", "$1veți"),
            new("[aă][sș]tia", "ăștia"),
            new("([Bb])[aă]gat(e|ele|elor|u[l]*|ului)?", "$1ăgat$2"),
            new("([Bb])[aă]nu[tț](i|ii|ilor|u[l]*|ului)", "$1ănuț$2"),
            new("([Bb])[aă]tut(e|ele|elor)?", "$1ătut$2"),
            new("([Bb])[aă]tu[tț](i|ii|ilor)", "$1ătuț$2"),
            new("([Bb])ine[iî]n[tț]eles", "$1ineînțeles"),
            new("([Bb])u[sș]te(an|anu[l]*|anului|ni|nilor)", "$1uște$2"),
            new("c[aă]c[aă]l[aă]u", "căcălău"),
            new("c[aă]l[aă]r(ea|eai|esc|im|ind|it|itu[l]*|itului)", "călăr$1"),
            new("c[aă]l[aă]re[țt](i|ii|ilor)", "călăreț$1"),
            new("c[aâ]m[aă]tar(i|ii|u[l]*|ului)?", "cămătar$1"),
            new("c[aă]rti(i|le|lor)*", "cărți$1"),
            new("c[aâ][sș]tig[aă]to(are|area|arele|arelor|r|ri|rii|rilor)", "câștigăto$1"),
            new("c[aâ][sș]tig(at|u[l]*|uri|urile|ului)?", "câștig$1"),
            new("c[aâ][tț]i", "câți"),
            new("([Cc])l[aă]dir(e|ea|i|ii|ile|ilor)", "$1lădir$2"),
            new("([Cc])on(struc|di)ti(a|e|ei|i|ile|ilor)", "$1on$2ți$3"),
            new("([Cc])r[aă]pat", "$1răpat"),
            new("cre[sș]t(erea|eri|erii|erilor)", "creșt$1"),
            new("([Cc])[aă] (am|imi|îmi)", "$1ă $2"),
            new("daca", "dacă"),
            new("d[aă]deam", "dădeam"),
            new("([Dd])[aă]r[aâ]m(e|i|at)?", "$1ărâm$2"),
            new("dezam[aă]geasc[aă]", "dezamăgească"),
            new("dezam[aă]g(esc|ire|irea|iri|irii|irilor|itoare|itoarele|itor|itori|itorii)", "dezamăg$1"),
            new("dezam[aă]ge[sș]t(e|i)", "dezamăgeșt$1"),
            new("dr[aă]gu[tț](a|e|ele|elor|u[l]*|ului)?", "drăguț$1"),
            new("e[sș]ti", "ești"),
            new("face[tț]i", "faceți"),
            new("([Ff])[aă]c(eai|eam|eau|ut|ute|utele|utelor|utu[l]*|utului)", "$1ăce$2"),
            new("([Ff])[aă]cea[tț]i", "$1ăceați"),
            new("f[aă]cu[sș][h]*i", "făcuși"),
            new("([Ff])[aă]cut(e|ele|elor)?", "$1ăcut$2"),
            new("([Ff])[aă]cut[aă]", "$1ăcută"),
            new("([Ff])erici[tț]i(i|lor)*", "$1ericiți$2"),
            new("([Ff])i[sș]ier(e|ele|elor)?", "$1ișier$2"),
            new("([Ff])unc[tț]i(a|e|ei|i|ile|ona|onal|onale|onalele|onali|onalii|onalilor|onar|onari|onarii|onarilor|onez|onezi)", "$1uncți$2"),
            new("func[tț]ioneaz[aă]", "funcționează"),
            new("func[tț]ioneaz[aă],", "funcționează,"),
            new("g[aă]le[tț]i(i|le|lor)*", "găleți$1"),
            new("([Gg])[aâ]nd(eam|esc|i|it|itor|u[l]*|uri|urile)?", "$1ând$2"),
            new("([Gg])[aâ]nde[sș]t(e|i)", "$1ândeșt$2"),
            new("([Gg])[aă]s(ea|eai|eam|esc|isem|it|ite)", "$1ăs$2"),
            new("([Gg])[aă]se[sș]t(e|i)", "$1ăseșt$2"),
            new("([Hh])ot[aă]r[aâ]t(e)?", "$1otărât$2"),
            new("([Hh])ot[aă]r[aâ][tț]i", "$1otărâți"),
            new("([Ii])[e3][sș]i(i|m|nd|re|rea|t|te)", "$1eși$2"),
            new("([Ii])[e3][sș]i[tț]i", "$1eșiți"),
            new("[iî]mpreun[aă]", "împreună"),
            new("[iî]n(ainte|alt|alte|apoi|apoiat|chid|chide|chis|chise|dobitocir(e|ea|ii|ilor)|dulci(t|te|rii)|flori(t|te|rii)|treb(are|area|i)*)", "în$1"),
            new("[iî]n(chinat|chis|(dobito|florea|dul)ceasc)[aă]", "în$1ă"),
            new("[iî]nc[aă]rcat(e)?", "încărcat$1"),
            new("[iî]nc(hinat|his)?[aă]", "înc$1ă"),
            new("[iî]ncerc([a-z]*)", "încerc$1"),
            new("[iî]ncurca(i|m|t|te|u)", "încurcat$1"),
            new("[iî]ncurc[aă]tur(a|i|ii|ile|ilor)", "încurcătur$1"),
            new("[iî]nrob(ire|irea|irii|it|ite)", "înrob$1"),
            new("[iî]nmul[tț](esc|i|im|ire|irea|ite)", "înmulț$1"),
            new("[iî]nsf[aâ]r[sș]it", "însfârșit"),
            new("[iî]nto(arce|arcere|rc|rci|rs)", "înto$1"),
            new("[iî]ntreba(i|m|re|rea)", "întreba$1"),
            new("[iî]ntreb[aă](m|ri|rii|rile|rilor|tor|toare|toarea|toarele|tori|torile)?", "întrebă$1"),
            new("[iî]n[tț]ele(g|ge|gi|pciune|pciunea|pciunii|pt|s|sul|sului|suri|surile)", "înțele$1"),
            new("[iî]nv[aă]ț(a|ai|am|au|t|te|tu[l]*|tului|tura|turi|turii|turile)", "învăț$1"),
            new("[iî][sș]i", "își"),
            new("[iî][tț]i", "îți"),
            new("([Jj])uc[aă]tor(ii|ilor|i|u[l]*|ului)?", "$1ucător$2"),
            new("([Ll])[aâ]ng[aă]", "$1ângă"),
            new("([Ll])[aă][tț]i(me|mea|mi|mile|milor|t|te|tele|tu[l]*|tului)?", "$1ăți$2"),
            new("([Ll])e[sș]in(a|ai|at|ate|atelor|atu[l]*|atului|u[l]*|ului)?", "$1eșin$2"),
            new("([Mm])[aă]car", "$1ăcar"),
            new("([Mm])aimu[tț](a|ei|ele|elor)", "$1aimuț$2"),
            new("([Mm])[aă]n[aâ]nc(e|i)?", "$1ănânc$2"),
            new("([Mm])[aă]n[aâ]nc[aă]", "$1ănâncă"),
            new("([Mm])[aâ]nc(a|at|ate)?", "$1ânc$2"),
            new("([Mm])[aă]reasc[aă]", "$1ărească"),
            new("m[aă]resc", "măresc"),
            new("m[aă]re[sș]t(e|i)", "măreșt$1"),
            new("mineaz[aă]", "minează"),
            new("([Mm])onstri(i|ilor)*", "$1onștri$2"),
            new("min[tț]i(i|le|lor|m|nd|t)*", "minți$1"),
            new("lini[sș]tit", "liniștit"),
            new("mi[sș]t(o[o]*|ocar|ocare|ocari|ocarilor)", "mișto$1"),
            new("mu[l]*[tț](i|umesc|umit|umite)", "mulț$1"),
            new("ni[sș]te", "niște"),
            new("omor[aâ]t(e|ele|elor)?", "omorât$1"),
            new("omor[aâ][tț](i|ii|ilor)", "omorâț$1"),
            new("ora[sș](e|ele|elor|u[l]*|ului)?", "oraș$1"),
            new("p[aă]dur(e|ea|i|ii|ile|ilor)", "pădur$1"),
            new("p[aă]m[aâ]nt(u[l]*|ului|uri|urile|urilor)?", "pământ$1"),
            new("p[aă]re(a|ai|am|m|re|rea|ri|rii|rile|rilor|rolog|rologi|rologia|rologie|rologii|rologilor)", "păre$1"),
            new("p[aă]rinte(le|lui|sc)?", "părinte$1"),
            new("p[aă]rin[tț]i(i|lor)*", "părinți$1"),
            new("piat[aă]", "piață"),
            new("pl[aâ]n(g|set|sete|setelor|su[l]*|sului)", "plân$1"),
            new("pl[aă]te[sș]t(e|i)", "plăteșt$1"),
            new("([Pp])e[sș]ter(a|i|ii|ile|ilor)", "$1eșter$2"),
            new("por[tț]i(a|e|ei|i|ilor|ona|onat|onate|onezi|une|unea|uni|unile|unilor)?", "porți$1"),
            new("po[tț]i", "poți"),
            new("po[tț]i sa", "poți să"),
            new("po[tț]iun(e|ea|i|ii|ilor)", "poțiun$1"),
            new("pr[aă]jit(e|uri|urilor)*", "prăjit$1"),
            new("pr[aă]v[aă]li(a|e|i|ile|ilor)", "prăvăli$1"),
            new("preg[aă]t(esc|ire|irea|it|ite)", "pregăt$1"),
            new("pre[sș]edint(a|e|ei|ele|elor|elui)?", "președint$1"),
            new("pre[tț](u[l]*|uri|urile|urilor)?", "preț$1"),
            new("func[tț]ional[aă]", "funcțională"),
            new("puie[tț]i(i|lor)*", "puieț$1"),
            new("pu[tț]in[aă]", "puțină"),
            new("pu[tț]in(e|i|ii)", "puțin$1"),
            new("([Rr])[aă]bdare(a)?", "$1ăbdare$2"),
            new("([Rr])[aă]bd[aă](m|ri|rii|rile|rilor|toare|toarele|tor|tori|torii)?", "$1ăbdă$2"),
            new("([Rr])[aă]m[aâ](i|n|n(e(a|a(m|u)*)*)*)", "$1ămâ$2"),
            new("([Rr])[aă]m[aâ]n[aă]", "$1ămână"),
            new("r[aă]spun(d|de|zi)", "răspun$1"),
            new("r[aă]spund[aă]", "răspundă"),
            new("([Rr])[aă]spunde(a)?[tț]i", "$1ăspunde$2ți"),
            new("([Rr])[aă]m[aâ]n(e|ea|em)?", "$1ămân$2"),
            new("([Rr])[aă]zboi(esc|m|nd|t|u[l]*|ului)", "$1ăzboi$2"),
            new("([Rr])o[sș]i(a|e|ei|i|ile|ilor|t|te|tele|tu[l]*|tului|u|u[l]*|ului)?", "$1oși$2"),
            new("[sș]andrama(ua)?", "șandrama$1"),
            new("([Ss])[aă]pun", "$1ăpun"),
            new("([Ss])[aă]rac(e|ele|elor|i|ii|ilor|u[l]*|ului)?", "$1ărac$2"),
            new("([Ss])[aă]ri[tț]i", "$1ăriți"),
            new("([Ss])[aă]tu(le|lele|li|lii|lilor|rat|rate|ratele)", "$1ătu$2"),
            new("([Ss])[aă]tura[tț]i(i|lor)*", "$1ăturați$2"),
            new("([Ss])emin[tț]e(le|lor)*", "$1emințe$2"),
            new("([Ss])c[aă]pat(e)?", "$1căpat$2"),
            new("([Ss])p[aâq]nzurat(e|ei|elor|u[l]*|ului)", "$1pânzurat$2"),
            new("([Ss])p[aâq]nzura[tț]i(i|ilor)", "$1pânzurați$2"),
            new("([Ss])tegule[tț](e|ele|elor|u[l]*|ului)", "$1steguleț$2"),
            new("[sș]ti(a|ai|am|e|i|im|u|ut|ute)*", "ști$1"),
            new("[sș]tiin[tț](a|e|ei|ele|elor|ific|ifice|ificelor)", "științ$1"),
            new("[sș]tiut[aă]", "știută"),
            new("([Ss])tr[aâ]m(b|be|bele|belor|t|te|tele|telor|toare|torii|toilor)", "$1trâm$2"),
            new("([Ss])tr[aâ]n(g|ge|geri|gerii|gerile|s|se|sele|selor|sori|sorile)", "$1trân$2"),
            new("[sș][tț]i(a|u)[tț]i", "ști$1ți"),
            new("[tț][aă]rc(u[l]*|ului|uri|urile|urilor)?", "țarc$1"),
            new("[tț][aă]ran(esc|i|ii|ilor|oi|oiu[l]*|oiului|u[l]*|ului)?", "țăran$1"),
            new("([Tt])[aâ]n[aă]ru[l]*(ui)?", "$1ânărul$2"),
            new("([Tt])[aâ]rn[aă]cop(u[l]*|ului)?", "$1ârnăcop$2"),
            new("([Tt])[aâ]rzi(e|i|u)", "$1ârzi$2"),
            new("([Tt])r[aă]ie[sș]t(e|i)", "$1răieșt$2"),
            new("[tț]i[ .-]a(i|m|r)", "ți-a$1"),
            new("[tț]i[ .-]a[sș]", "ți-aș"),
            new("[tț]igan(i|ii|ilor|u[l]*|ului)", "țigan$1"),
            new("([Tt])ovar[aă][sș](e|ele|elor|i|ii|ilor)", "$1ovarăș$2"),
            new("([Uu])r[aă]sc", "$1răsc"),
            new("([Uu])r[aâ]t(e|ei|elor|u[l]*|ului)?", "$1rât$2"),
            new("([Uu])r[aâ][tț]i(i|lor)*", "$1râți$2"),
            new("([Uu])rca[tț]i(i|lor)*", "$1rcați$2"),
            new("([Uu])rm[aă]r(ea|eai|esc|im|ind|ire|irea|iri|irii|irilor|it|itoare|itoarei|itoarele|itoarelor|itor|itori|itorilor)", "$1rmăr$2"),
            new("([Uu])[sș]or", "$1șor"),
            new("([Vv])[aă](d|dit|dite|zui|zut)", "$1ă$2"),
            new("([Vv])[aâ]rst(a|e|ei|ele|elor|nic|nice|nicele|nicelor|nicu[l]*|nicului)", "$1ârst$2"),
            new("updateaz[aă]", "actualizează"),
            new("updat(ez|eze|ezi)", "actualiz$1"),
            new("([Zz])[aâ]gan(e|esc|i|ic|ii|ilor|u[l]*|ului)?", "$1âgan$2"),
            new("([Aa]lt[aă]|[Cc]e|[Ff]emei[ae]|[Ff]oarte|[Mm]ai|[Nn]u|[Oo]|[Oo]ai[ae]|[Pp]rima|[Ss][ăe]|[Uu]ltima|[Vv]opsea) (barc|bun|cas|[Dd]at|gr[aă]mad|joac|limb|neagr|poft|singur|treab|v(in)*)[aă][aă]*", "$1 $2ă"),
            new("([Aa]nu[l]*) asta", "$1 ăsta"),
            new("([Aa]uzit|[Cc](auza|re(d[e]*[a]*|(i|ut))|um)|[Uu]itat|[Vv]ezi) ca", "$1 că"),
            new("([Aa])[sș] prefera", "$1ș prefera"),
            new("([Cc][ae]|[Hh]|[Pp]are|[Vv]re(a|au|i|m|[tț]i)) [sș][aăâq]", "$1 să"),
            new("([Dd]racu|[Pp]refera) sa", "$1 să"),
            new("([Cc]u) [sș][aăâq]", "$1 șa"),
            new("([Pp]are|[Ss]imt[aăe]*) r[aă]u", "$1 rău"),
            new("b[aă]i (termale)", "băi $1"),
            new("buna ([sz]iua)", "bună $1"),
            new("([Cc])[aă] (avem|e|este|îi|merg|nu|o să|oricum|se|sunt(em)*|v[aă]|zice[a]*)", "$1ă $2"),
            new("d[aă] ([aă][sș]t[ei]a)", "dă $1"),
            new("([Pp])[aâ]n[aă] (acum|astăzi|atunci|azi|ieri|mâine|săptămâna)", "$1ână $2"),
            new("([Pp])oft[aă] ([Bb]un[aă])", "$1oftă $2"),
            new("([Ss])[aă] ([Ff](ac[ăi]*|ie)|[iî][mtț]i|[Vv]ezi)", "$1ă $2"),
            new("([Ss])ear[aă] ([Ff]ain[aă])", "$1eară $2"),
            new("([Vv])[aă] ([Cc]ulca[tț]i|[Ll]as|[Rr]og|[Ss]upărați)", "$1ă $2"),
            new("([Cc])[aâ]t", "$1ât"),
            new("I(i|l|mi|n|s)", "Î$1"),
            new("i(i|l|mi|n|s)", "î$1"),
            new("Si", "Și"),
            new("si", "și"),
            new("Tie", "Ție"),
            new("tie", "ție"),
            new("Tin", "Țin"),
            new("tin", "țin"),
            new("o problema", "o problemă"),
            new("[Pp]ite[sș]ti", "Pitești"),
            new("[Pp]okemon", "Pokémon")
        ];

        return values;
    }
}