using System.Collections.Generic;
using NuciText.Grammar.Rules;

namespace NuciText.Grammar.Romanian.Rules;

/// <summary>
/// Fixes common Romanian chat typos.
/// </summary>
internal sealed class RomanianTypoFixRule : PatternReplacementRuleBase
{
    static readonly IReadOnlyList<RegexReplacement> replacements =
    [
        new("da[ .0-]*[ ]*mi[.-]*[ ]*l", "dă-mi-l"),
        new("dal[ .0-]*ar", "dal-ar"),
        new("d[aq][ .0-]*mi", "dă-mi"),
        new("du[ .0-]*ca[ .-]*sa", "ducă-să"),
        new("du[ .0-]*m[aă]", "du-mă"),
        new("du[ .0-]*mi", "du-mi"),
        new("du[ .0-]*mi[ .-]*l", "du-mi-l"),
        new("du[ .0-]*te", "du-te"),
        new("du[ .0-]*c[aă][ .-]*s[aă]", "ducă-să"),
        new("([Ff])[aăq][ .0-]*(i|l|le|mi|[tț]i)", "$1ă-$2"),
        new("([Ff])[aq]cut[ .0-]*o", "$1ăcut-o"),
        new("([Ff])ir[ .0-]*a(i|r|m|[tț]i)", "$1ir-$2"),
        new("([Ii])[.0-]*[ ]*[aq](i|m)", "$1-a$2"),
        new("[iî][.-]*[ ]*mi", "îmi"),
        new("[iî]ntr[ .0-]o", "într-o"),
        new("([Ll])[aq]s[aăq][ .0-]*mi[ .0-]*(l|le|o)", "$1asă-mi-$2"),
        new("([Ll])[.0-]*[ ]*([aq]i|[aq]r|[aq]m|[aq]u|oi)", "$1-$2"),
        new("([Ll])[.0-]*[ ]*[aq]+(i|r|m|u)", "$1-a$2"),
        new("m[.0-][aq]i", "m-ai"),
        new("m[.0-]*[ ]*[aq]i (am|are|dă|e)", "mai $1"),
        new("m[.0-]*[ ]*[aq]m", "m-am"),
        new("m[.0-]*[ ]*[aq][tț]i", "m-ați"),
        new("m[.0-]*[ ]*[aq]r interesa", "m-ar interesa"),
        new("([Mm])i[ .0-]*([aq]i|[aq]m|[aq]r|au|l|o)", "$1i-$2"),
        new("([Nn])[.0-]*[ ]*[aq][.0-]*[ ]*(i|m|r|re|u)", "$1-a$2"),
        new("([Nn])e[ .0-]*ai", "$1e-ai"),
        new("([Nn])u[ .0-]*i", "$1u-i"),
        new("([Ss])[ .0-](a|au|o|or)", "$1-$2"),
        new("([Ss])[aăq][ .0-]*mi", "$1ă-mi"),
        new("([Ss])[aăq][ .0-]*[sș]i", "$1ă-și"),
        new("([Ss])[aăq][ .0-]*[tț]i", "$1ă-ți"),
        new("([Vv])[ .0-]*[aq][tț]i", "$1-ați"),
        new("([Zz])i[.0-]*mi", "$1-mi"),
        new("([Gg])[aă]sit[ .0-]*o", "$1ăsit-o"),
        new("([Rr])oag[aă][ .0-]*te", "$1oagă-te"),
        new("d[ ]*alea", "din alea"),
        new("din[aăq]la", "din ăla"),
        new("[iî]nloc", "în loc"),
        new("([Aa])bea", "$1bia"),
        new("[aq]cas", "acasă"),
        new("[aq]cmw", "acum"),
        new("[aq]dioc[aă]", "adică"),
        new("[aq](jung|m|st[e]*a)", "a$1"),
        new("([Aa])diă", "$1dică"),
        new("aier(at|e|ele|elor|u|ul|ului)?", "aer$1"),
        new("([Aa])li[g]*nia[g]*mentu[l]*", "$1liniamentul"),
        new("anlu", "anul"),
        new("arete", "arate"),
        new("artific", "artificiu"),
        new("artificuri(le|lor)*", "artificii$1"),
        new("aste", "astea"),
        new("([Bb])ine venit", "$1inevenit"),
        new("c[aâăq]c[aq]te", "câcaturi"),
        new("ceaw", "ceau"),
        new("([Cc])hsti([a-z]*)*", "$1hesti$2"),
        new("([Cc])rec[aăq]", "$1red că"),
        new("creiat", "creat"),
        new("creiez", "creez"),
        new("cva", "ceva"),
        new("([Dd])ada", "$1a da"),
        new("d[.0-]*[ ]*aia", "de aia"),
        new("([Ee])ra dec[aâ]t", "$1ra doar"),
        new("([Ee])(cs|x)teriro", "$1xterior"),
        new("([Ff])[aă]ceaut", "$1ăcut"),
        new("[iî]ncur[aâq]nd", "în curând"),
        new("lu", "lui"),
        new("([Ll])ucr(e|i)", "$1ucre$2"),
        new("lag[g]*(u|ul|ului)?", "lag$1"),
        new("mqna", "mâna"),
        new("([Mm])ul[tț]umes(c)?", "$1ulțumesc"),
        new("naibi", "naibii"),
        new("([Oo])ricunde", "$1riunde"),
        new("([Pp])[aăq]du[rs]e", "$1ădure"),
        new("([Pp])ie[tț]ii", "$1ieței"),
        new("([Pp])qi", "$1oi"),
        new("([Pp])[aăq]i[aăq]n[gj][aăq]n", "$1aianjen"),
        new("([Pp])rim[aqă]r", "$1rimar"),
        new("pten", "prieten"),
        new("puțîn", "puțin"),
        new("(rtebuie|trebe)", "trebuie"),
        new("siua", "ziua"),
        new("supsol", "subsol"),
        new("([Tt])to", "$1ot"),
        new("[tț]io", "ți-o"),
        new("uameni", "oameni"),
        new("uitate", "uită-te"),
        new("vi la", "vii la"),
        new("vaciile", "vacile"),
        new("([Vv])ejnici(a|e|ei)", "$1eșnici$2"),
        new("vizavi", "vis-à-vis"),
        new("vr[ew3](a|i)", "vre$1"),
        new("vroi(a|ai|ați|am)", "voi$1"),
        new("acu merg", "acum merg"),
        new("abi mi-am", "abea mi-am"),
        new("ban ide", "bani de"),
        new("dac [aă]ai", "dacă ai"),
        new("maia (m|re)", "mai a$1"),
        new("([Pp])r[aă]duie([sș]te)?", "$1rădează"),
        new("(are|trebuie) dec[aâ]t", "$1 doar"),
        new("acm", "acum"),
        new("avd", "văd"),
        new("blocku", "blocul"),
        new("grwu", "greu"),
        new("interesn", "interesant"),
        new("inventoryu", "inventarul"),
        new("nmc", "nimic"),
        new("unlu", "unul"),
        new("(it|what) îs", "$1 is"),
        new("([Aa])rmor", "$1rmour"),
        new("chisel[l]*e[d]*", "chiseled"),
        new("dangeon", "dungeon"),
        new("haiway", "highway"),
        new("nausia", "nausea"),
        new("ownar", "owner"),
        new("thouse", "those"),
        new("traider", "trader"),
        new("vbinde", "vinde"),
        new("villiger([a-z])*", "villager$1")
    ];

    /// <inheritdoc/>
    public override string Id => "romanian-typo-fix";

    /// <inheritdoc/>
    public override string Description => "Fixes common Romanian chat typos and shorthand spelling mistakes.";

    /// <inheritdoc/>
    protected override string DoApply(string text)
        => ApplyWordReplacements(text, replacements);
}