using System.Collections.Generic;
using NuciText.Grammar.Rules;

namespace NuciText.Grammar.Romanian.Rules;

/// <summary>
/// Fixes common Romanian chat typos.
/// </summary>
internal sealed class RomanianTypoFixRule : PatternReplacementRuleBase
{
    static readonly IReadOnlyList<RegexReplacement> replacements =
    [
        new("([Aa])bea", "$1bia"),
        new("([Aa])diă", "$1dică"),
        new("([Aa])li[g]*nia[g]*mentu[l]*", "$1liniamentul"),
        new("([Aa])rmor", "$1rmour"),
        new("([Bb])ine venit", "$1inevenit"),
        new("([Cc])hsti([a-z]*)*", "$1hesti$2"),
        new("([Cc])rec[aăq]", "$1red că"),
        new("([Dd])ada", "$1a da"),
        new("([Ee])(cs|x)teriro", "$1xterior"),
        new("([Ee])ra dec[aâ]t", "$1ra doar"),
        new("([Ff])[aă]ceaut", "$1ăcut"),
        new("([Ff])[aăq][ .0-]*(i|l|le|mi|[tț]i)", "$1ă-$2"),
        new("([Ff])[aq]cut[ .0-]*o", "$1ăcut-o"),
        new("([Ff])ir[ .0-]*a(i|r|m|[tț]i)", "$1ir-$2"),
        new("([Gg])[aă]sit[ .0-]*o", "$1ăsit-o"),
        new("([Ii])[.0-]*[ ]*[aq](i|m)", "$1-a$2"),
        new("([Ll])[.0-]*[ ]*([aq]i|[aq]r|[aq]m|[aq]u|oi)", "$1-$2"),
        new("([Ll])[.0-]*[ ]*[aq]+(i|r|m|u)", "$1-a$2"),
        new("([Ll])[aq]s[aăq][ .0-]*mi[ .0-]*(l|le|o)", "$1asă-mi-$2"),
        new("([Ll])ucr(e|i)", "$1ucre$2"),
        new("([Mm])i[ .0-]*([aq]i|[aq]m|[aq]r|au|l|o)", "$1i-$2"),
        new("([Mm])ul[tț]umes(c)?", "$1ulțumesc"),
        new("([Nn])[.0-]*[ ]*[aq][.0-]*[ ]*(i|m|r|re|u)", "$1-a$2"),
        new("([Nn])e[ .0-]*ai", "$1e-ai"),
        new("([Nn])u[ .0-]*i", "$1u-i"),
        new("([Oo])ricunde", "$1riunde"),
        new("([Pp])[aăq]du[rs]e", "$1ădure"),
        new("([Pp])[aăq]i[aăq]n[gj][aăq]n", "$1aianjen"),
        new("([Pp])ie[tț]ii", "$1ieței"),
        new("([Pp])qi", "$1oi"),
        new("([Pp])r[aă]duie([sș]te)?", "$1rădează"),
        new("([Pp])rim[aqă]r", "$1rimar"),
        new("([Rr])oag[aă][ .0-]*te", "$1oagă-te"),
        new("([Ss])[ .0-](a|au|o|or)", "$1-$2"),
        new("([Ss])[aăq][ .0-]*[sș]i", "$1ă-și"),
        new("([Ss])[aăq][ .0-]*[tț]i", "$1ă-ți"),
        new("([Ss])[aăq][ .0-]*mi", "$1ă-mi"),
        new("([Tt])to", "$1ot"),
        new("([Vv])[ .0-]*[aq][tț]i", "$1-ați"),
        new("([Vv])ejnici(a|e|ei)", "$1eșnici$2"),
        new("([Zz])i[.0-]*mi", "$1-mi"),
        new("(are|trebuie) dec[aâ]t", "$1 doar"),
        new("(it|what) îs", "$1 is"),
        new("(rtebuie|trebe)", "trebuie"),
        new("[aq](jung|m|st[e]*a)", "a$1"),
        new("[aq]cas", "acasă"),
        new("[aq]cmw", "acum"),
        new("[aq]dioc[aă]", "adică"),
        new("[iî][.-]*[ ]*mi", "îmi"),
        new("[iî]ncur[aâq]nd", "în curând"),
        new("[iî]nloc", "în loc"),
        new("[iî]ntr[ .0-]o", "într-o"),
        new("[tț]io", "ți-o"),
        new("\\? io", "? Io"),
        new("abi mi-am", "abea mi-am"),
        new("aci", "aici"),
        new("acm", "acum"),
        new("acu", "acum"),
        new("acu merg", "acum merg"),
        new("afut", "avut"),
        new("ai dat", "ai dat"),
        new("aier(at|e|ele|elor|u|ul|ului)?", "aer$1"),
        new("ălea", "alea"),
        new("ala", "ăla"),
        new("ami", "a-mi"),
        new("altcv", "altceva"),
        new("amu ", "acum "),
        new("amu", "acum"),
        new("anlu", "anul"),
        new("arete", "arate"),
        new("artific", "artificiu"),
        new("artificuri(le|lor)*", "artificii$1"),
        new("asa", "așa"),
        new("asai,", "așa-i,"),
        new("asai", "așa-i"),
        new("asi", "aș"),
        new("aste", "astea"),
        new("avd", "văd"),
        new("baga", "bagă"),
        new("ban ide", "bani de"),
        new("blocku", "blocul"),
        new("bosi", "boși"),
        new("bosilor", "boșilor"),
        new("bunavointa", "bunăvoința"),
        new("c[aâăq]c[aq]te", "câcaturi"),
        new("o cabana", "o cabană"),
        new("cand ", "când "),
        new("capacele", "capacele"),
        new("casuta", "căsuța"),
        new("casutei", "căsuței"),
        new("cealalt", "celălalt"),
        new("ceaw", "ceau"),
        new("celalalt", "celălalt"),
        new("cemi", "ce-mi"),
        new("cladire, probabil", "clădire, probabil"),
        new("chisel[l]*e[d]*", "chiseled"),
        new("cladire", "clădire"),
        new("co", "c-o"),
        new("colo", "acolo"),
        new("conacu", "conacul"),
        new("conducatorii", "conducătorii"),
        new("copiaza", "copiază"),
        new("corectez", "corectez"),
        new("corecteza", "corectează"),
        new("corupti", "corupți"),
        new("crapa in patru", "crapă în patru"),
        new("crapa in", "crapă în"),
        new("crapa", "crapă"),
        new("creiat", "creat"),
        new("creiez", "creez"),
        new("csf", "ce să fac"),
        new("csz,", "ce să zic,"),
        new("csz", "ce să zic"),
        new("cupru", "cupru"),
        new("cva", "ceva"),
        new("d aia", "d-aia"),
        new("d[ ]*alea", "d-alea"),
        new("d[.0-]*[ ]*aia", "d-aia"),
        new("d[aq][ .0-]*mi", "dă-mi"),
        new("da[ .0-]*[ ]*mi[.-]*[ ]*l", "dă-mi-l"),
        new("dac [aă]ai", "dacă ai"),
        new("daia", "d-aia"),
        new("dal[ .0-]*ar", "dal-ar"),
        new("dala", "d-ăla"),
        new("dangeon", "dungeon"),
        new("dc", "de ce"),
        new("de ce da", "de ce, dar"),
        new("de-am spart", "de-am spart"),
        new("deam", "de-am"),
        new("deati", "de-ați"),
        new("decat ", "decât "),
        new("destept", "deștept"),
        new("din[aăq]la", "din ăla"),
        new("drumu", "drumul"),
        new("du[ .0-]*c[aă][ .-]*s[aă]", "ducă-să"),
        new("du[ .0-]*ca[ .-]*sa", "ducă-să"),
        new("du[ .0-]*m[aă]", "du-mă"),
        new("du[ .0-]*mi", "du-mi"),
        new("du[ .0-]*mi[ .-]*l", "du-mi-l"),
        new("du[ .0-]*te", "du-te"),
        new("esti ", "ești "),
        new("esti tu", "ești tu"),
        new("esti", "ești"),
        new("facea", "făcea"),
        new("faceam", "făceam"),
        new("fati", "fă-ți"),
        new("fă-ti", "fă-ți"),
        new("fereasca", "ferească"),
        new("fi bogat", "fii bogat"),
        new("fimiar", "fi-mi-ar"),
        new("fisa", "fisă"),
        new("fo ", "fost "),
        new("fo la", "fost la"),
        new("fo,", "fost,"),
        new("fo", "fost"),
        new("formatu gresit", "formatul greșit"),
        new("formatu", "formatul"),
        new("fraieru", "fraierul"),
        new("furnicutele se", "furnicuțele se"),
        new("ghiozdanu", "ghiozdanul"),
        new("gradina", "grădina"),
        new("gresit", "greșit"),
        new("anapoi", "înapoi"),
        new("grwu", "greu"),
        new("habar nam", "habar n-am"),
        new("habar nam,", "habar n-am,"),
        new("haiway", "highway"),
        new("ii buna", "îi bună"),
        new("îi buna", "îi bună"),
        new("ii lasi", "ii lași"),
        new("il voi lasa", "îl voi lăsa"),
        new("lasal", "lasă-l"),
        new("inca", "încă"),
        new("inot", "înot"),
        new("inseamna", "înseamnă"),
        new("interesn", "interesant"),
        new("intra", "intră"),
        new("intrun palat", "într-un palat"),
        new("intrun", "într-un"),
        new("intruna", "întruna"),
        new("inventoryu", "inventarul"),
        new("io ", "eu "),
        new("io le", "eu le"),
        new("io", "eu"),
        new("iti", "îți"),
        new("labile", "labele"),
        new("lag[g]*(u|ul|ului)?", "lag$1"),
        new("lo", "l-o"),
        new("lu", "lui"),
        new("m[.0-][aq]i", "m-ai"),
        new("m[.0-]*[ ]*[aq][tț]i", "m-ați"),
        new("m[.0-]*[ ]*[aq]i (am|are|dă|e)", "mai $1"),
        new("m[.0-]*[ ]*[aq]m", "m-am"),
        new("m[.0-]*[ ]*[aq]r interesa", "m-ar interesa"),
        new("mai vad", "mai văd"),
        new("maia (m|re)", "mai a$1"),
        new("malu", "malul"),
        new("mare ca", "mare că"),
        new("mă tot", "mă tot"),
        new("măcar sa", "măcar să"),
        new("merem", "mergem"),
        new("mergea decat", "mergea decât"),
        new("mergea mai", "mergea mai"),
        new("mesaju", "mesajul"),
        new("mi so", "mi s-a"),
        new("mi-ai", "mi-ai"),
        new("mio", "mi-o"),
        new("miai", "mi-ai"),
        new("miam scos", "mi-am scos"),
        new("miau", "mi-au"),
        new("mo ", "m-a "),
        new("mo", "m-a"),
        new("mqna", "mâna"),
        new("n-ar fi greu", "nu ar fi greu"),
        new("nai", "n-ai"),
        new("nentoarcem", "ne-ntoarcem"),
        new("naibi", "naibii"),
        new("najung lemnele mai taie", "nu ajung lemnele, mai taie"),
        new("nam", "n-am"),
        new("nar", "n-ar"),
        new("nare", "n-are"),
        new("sa n-are", "sa nu are"),
        new("sa nare", "sa nu are"),
        new("nausia", "nausea"),
        new("navea", "n-avea"),
        new("navem", "n-avem"),
        new("naveti", "n-aveți"),
        new("nmc", "nimic"),
        new("nmn", "nimeni"),
        new("no sa", "nu o să"),
        new("no", "n-o"),
        new("noastra", "noastră"),
        new("nostri", "noștri"),
        new("noua", "nouă"),
        new("nstie", "nu știe"),
        new("nu ști", "nu știi"),
        new("nu știu ca", "nu știu că"),
        new("nu știu dc", "nu știu de ce"),
        new("nui", "nu-i"),
        new("nus", "nu-s"),
        new("nusi", "nu-și"),
        new("nuti", "nu-ți"),
        new("orasel", "orășel"),
        new("orasele", "orășele"),
        new("oraselele", "orășelele"),
        new("ownar", "owner"),
        new("padurea", "pădurea"),
        new("pamantean", "pământean"),
        new("pana-i", "până-i"),
        new("o parcela", "o parcelă"),
        new("piata", "piața"),
        new("piatra, piatra", "piatra, piatra"),
        new("planuit", "plănuit"),
        new("po", "p-o"),
        new("pokemon", "Pokémon"),
        new("numa", "numai"),
        new("numai bogați", "numai bogații"),
        new("pten", "prieten"),
        new("puțîn", "puțin"),
        new("tn", "tine"),
        new("sambata", "sâmbăta"),
        new("sami", "să-mi"),
        new("santem", "suntem"),
        new("sar face", "s-ar face"),
        new("o sa", "o să"),
        new("o sati", "o să-ți"),
        new("sa corectez", "să corectez"),
        new("sasi", "să-și"),
        new("sati", "să-ți"),
        new("scarba", "scârbă"),
        new("semneaza", "semnează"),
        new("sentampla", "se întâmplă"),
        new("sfantu", "sfântul"),
        new("si io", "și eu"),
        new("siau", "și-au"),
        new("sior", "și-or"),
        new("[sș]i[tț]i", "și-ți"),
        new("siua", "ziua"),
        new("so mai", "s-o mai"),
        new("so schimb", "s-o schimb"),
        new("so", "s-o"),
        new("softvare", "software"),
        new("spatele", "spatele"),
        new("stie", "știe"),
        new("stim", "știm"),
        new("strang", "strâng"),
        new("sub fereastra", "sub fereastră"),
        new("supsol", "subsol"),
        new("taiat", "tăiat"),
        new("tarta", "tartă"),
        new("terminat", "terminat"),
        new("testam ca", "testam că"),
        new("trmin", "termin"),
        new("pacat ca", "păcat că"),
        new("thouse", "those"),
        new("tipat", "țipat"),
        new("toata", "toată"),
        new("traider", "trader"),
        new("tranta", "trântă"),
        new("tranteasca", "trântească"),
        new("trantesc", "trântesc"),
        new("trânta", "trântă"),
        new("trnacop", "târnăcop"),
        new("trota afara", "trotineta afară"),
        new("trotineta afară", "trotineta afară"),
        new("scos trotinetă", "scos trotineta"),
        new("trota", "trotineta"),
        new("trote", "trotinete"),
        new("uameni", "oameni"),
        new("uita-te", "uită-te"),
        new("uitate", "uită-te"),
        new("un mar", "un măr"),
        new("unlu", "unul"),
        new("urata", "urâtă"),
        new("vaciile", "vacile"),
        new("valu", "valul"),
        new("vam", "v-am"),
        new("vantu", "vântul"),
        new("vati", "v-ați"),
        new("vbinde", "vinde"),
        new("vi la", "vii la"),
        new("villiger([a-z])*", "villager$1"),
        new("visita", "vizită"),
        new("vizavi", "vis-à-vis"),
        new("gat", "gât"),
        new("vr[ew3](a|i)", "vre$1"),
        new("vrea si io", "vrea și eu"),
        new("vreau", "vreau"),
        new("vriau", "vreau"),
        new("vroi(a|ai|a[tț]i|am|au)", "voi$1"),
        new("sio gatat", "și-a terminat"),
        new("sio", "și-a"),
        new("tiam", "ți-am"),
        new("tiar", "ți-ar"),
        new("tipu", "tipul"),
        new("salutarile", "salutările"),
        new("schimbarile", "schimbările"),
        new("numa ", "numai "),
        new("linistit", "liniștit"),
        new("gasesc", "găsesc"),
        new("cirese", "cireșe"),
        new("cresti", "crești"),
        new("veniti", "veniți"),
        new("totii", "toții"),
    ];

    /// <inheritdoc/>
    public override string Id => "romanian-typo-fix";

    /// <inheritdoc/>
    public override string Description => "Fixes common Romanian chat typos and shorthand spelling mistakes.";

    /// <inheritdoc/>
    protected override string DoApply(string text)
        => ApplyWordReplacements(text, replacements);
}