using System;
using NUnit.Framework;

namespace NuciText.Grammar.Romanian.UnitTests.Rules;

[TestFixture]
public class RomanianDiacriticsRuleTests
{
    [TestCase("actualizeaza", "actualizează")]
    [TestCase("adoarma", "adoarmă")]
    [TestCase("ajuti", "ajuți")]
    [TestCase("aliniaza", "aliniază")]
    [TestCase("amanam", "amânam")]
    [TestCase("apartine", "aparține")]
    [TestCase("aprinda", "aprindă")]
    [TestCase("aprinsi", "aprinși")]
    [TestCase("as prefera", "aș prefera")]
    [TestCase("asa", "așa")]
    [TestCase("ascunsa", "ascunsă")]
    [TestCase("balanta", "balanța")]
    [TestCase("barcuta", "bărcuța")]
    [TestCase("bosi", "boși")]
    [TestCase("bosii", "boșii")]
    [TestCase("bosilor", "boșilor")]
    [TestCase("ca am", "că am")]
    [TestCase("ca imi", "că îmi")]
    [TestCase("cacat", "câcat")]
    [TestCase("caine", "câine")]
    [TestCase("castigam", "câștigam")]
    [TestCase("castigat", "câștigat")]
    [TestCase("catel", "cățel")]
    [TestCase("cateva", "câteva")]
    [TestCase("cateva", "câteva")]
    [TestCase("cirese", "cireșe")]
    [TestCase("citeasca", "citească")]
    [TestCase("cladire", "clădire")]
    [TestCase("completeaza", "completează")]
    [TestCase("concentreaza", "concentrează")]
    [TestCase("consideratie", "considerație")]
    [TestCase("corecteaza", "corectează")]
    [TestCase("cresti", "crești")]
    [TestCase("cunoastere", "cunoaștere")]
    [TestCase("daca", "dacă")]
    [TestCase("defileaza", "defilează")]
    [TestCase("definite", "definiție")]
    [TestCase("democratia", "democrația")]
    [TestCase("dependinta", "dependința")]
    [TestCase("deschisa", "deschisă")]
    [TestCase("distributie", "distribuție")]
    [TestCase("esti", "ești")]
    [TestCase("estimeaza", "estimează")]
    [TestCase("facea", "făcea")]
    [TestCase("faceam", "făceam")]
    [TestCase("faceti", "faceți")]
    [TestCase("fereasca", "ferească")]
    [TestCase("fleosc", "fleoșc")]
    [TestCase("fondata", "fondată")]
    [TestCase("frisca", "frișca")]
    [TestCase("functionala", "funcțională")]
    [TestCase("functioneaza,", "funcționează,")]
    [TestCase("functioneaza", "funcționează")]
    [TestCase("furnicutele", "furnicutele")]
    [TestCase("garzii", "gărzii")]
    [TestCase("gasesc", "găsesc")]
    [TestCase("gradinita", "grădinița")]
    [TestCase("greseasca", "gresească")]
    [TestCase("greselile", "greșelile")]
    [TestCase("hranesc", "hrănesc")]
    [TestCase("impartit", "împărțit")]
    [TestCase("impreuna", "împreună")]
    [TestCase("imprumut", "împrumut")]
    [TestCase("incearca", "încearcă")]
    [TestCase("incepem", "începem")]
    [TestCase("ingrijorare", "îngrijorare")]
    [TestCase("inlocuiasca", "înlocuiască")]
    [TestCase("inot", "înot")]
    [TestCase("inseamna", "înseamnă")]
    [TestCase("intoarce", "întoarce")]
    [TestCase("intreaga", "întreaga")]
    [TestCase("iteratia", "iterația")]
    [TestCase("iuti", "iuți")]
    [TestCase("jucatoarele", "jucătorarele")]
    [TestCase("libertatii", "libertății")]
    [TestCase("logheaza", "loghează")]
    [TestCase("mananc", "mănânc")]
    [TestCase("mancare", "mâncare")]
    [TestCase("mentenanta", "mentenanța")]
    [TestCase("mentin", "mențin")]
    [TestCase("mineaza", "minează")]
    [TestCase("minereasca", "minerească")]
    [TestCase("munceasca", "muncească")]
    [TestCase("muntii", "munții")]
    [TestCase("muti", "muți")]
    [TestCase("nationale", "naționale")]
    [TestCase("natiune", "națiune")]
    [TestCase("niste", "niște")]
    [TestCase("nivelata", "nivelată")]
    [TestCase("noastra", "noastră")]
    [TestCase("noptii", "nopții")]
    [TestCase("noștri", "noștri")]
    [TestCase("odata", "odată")]
    [TestCase("odihneasca", "odihnească")]
    [TestCase("odinioara", "odinioară")]
    [TestCase("orasel", "orășel")]
    [TestCase("orasele", "orașele")]
    [TestCase("oraselele", "orășelele")]
    [TestCase("orasu", "orașu")]
    [TestCase("oua", "ouă")]
    [TestCase("pacat", "păcat")]
    [TestCase("pacate", "păcate")]
    [TestCase("pacatosule", "păcătosule")]
    [TestCase("palmuit", "pălmuit")]
    [TestCase("pamant", "pământ")]
    [TestCase("pamantean", "pământean")]
    [TestCase("parea", "părea")]
    [TestCase("parerea", "părerea")]
    [TestCase("piata", "piața")]
    [TestCase("placere", "plăcere")]
    [TestCase("planuiesti", "plănuiești")]
    [TestCase("planuit", "plănuit")]
    [TestCase("poti sa", "poți să")]
    [TestCase("poti", "poți")]
    [TestCase("prefera sa", "prefera să")]
    [TestCase("pregatit", "pregătit")]
    [TestCase("primarie", "primărie")]
    [TestCase("puna", "pună")]
    [TestCase("rabdare", "răbdare")]
    [TestCase("raman", "rămân")]
    [TestCase("ramas", "rămas")]
    [TestCase("raspunsului", "răspunsului")]
    [TestCase("recunoasca", "recunoască")]
    [TestCase("reductie", "reducție")]
    [TestCase("renuntam", "renunțăm")]
    [TestCase("reusim", "reușim")]
    [TestCase("ridicata", "ridicată")]
    [TestCase("roscata", "roșcata")]
    [TestCase("rugaciune", "rugăciune")]
    [TestCase("ruleaza", "rulează")]
    [TestCase("sambata", "sâmbăta")]
    [TestCase("sansa", "șansa")]
    [TestCase("saptamana", "săptămâna")]
    [TestCase("saraca", "săraca")]
    [TestCase("saracii", "săracii")]
    [TestCase("saracilor", "săracilor")]
    [TestCase("saracit", "săracit")]
    [TestCase("sarat", "sărat")]
    [TestCase("sarbatoare", "sărbătoare")]
    [TestCase("sarit", "sărit")]
    [TestCase("sarpe", "șarpe")]
    [TestCase("scoasa", "scoasă")]
    [TestCase("scobeste", "scobește")]
    [TestCase("scolile", "școlile")]
    [TestCase("scuzati", "scuzați")]
    [TestCase("semneaza", "semnează")]
    [TestCase("serupit", "șerpuit")]
    [TestCase("sfarseasca", "sfârșească")]
    [TestCase("sfinteasca", "sfințească")]
    [TestCase("slefuit", "șlefuit")]
    [TestCase("slefuita", "șlefuita")]
    [TestCase("spalat", "spălat")]
    [TestCase("sparga", "spargă")]
    [TestCase("spatiu", "spațiu")]
    [TestCase("stanga", "stânga")]
    [TestCase("starneste", "stârnește")]
    [TestCase("stiu", "știu")]
    [TestCase("stramt", "strâmt")]
    [TestCase("stropeasca", "stropească")]
    [TestCase("susta", "șusta")]
    [TestCase("taieri", "tăieri")]
    [TestCase("tarnacop", "târnăcop")]
    [TestCase("teava", "țeava")]
    [TestCase("teleporteaza", "teleportează")]
    [TestCase("temnita", "temnița")]
    [TestCase("temnite", "temnițe")]
    [TestCase("tipai", "țipai")]
    [TestCase("tipam", "țipam")]
    [TestCase("tipat", "țipat")]
    [TestCase("totii", "toții")]
    [TestCase("totusi", "totuși")]
    [TestCase("trantesc", "trântesc")]
    [TestCase("trânteasca", "trântească")]
    [TestCase("urmaresc", "urmăresc")]
    [TestCase("vamala", "vamală")]
    [TestCase("veniti", "veniți")]
    [TestCase("viata", "viața")]
    [TestCase("vietii", "vieții")]
    [TestCase("voiasca", "voiască")]
    [TestCase("voiati", "voiați")]
    [TestCase("vopseasca", "vopsească")]
    [TestCase("vorbeasca", "vorbească")]
    [TestCase("voteaza", "votează")]
    [TestCase("voua", "vouă")]
    [TestCase("vreti", "vreți")]
    public void Apply_AddsExpectedDiacritics(string text, string expected)
    {
        IGrammarRule rule = CreateRule("NuciText.Grammar.Romanian.Rules.RomanianDiacriticsRule");

        string result = rule.Apply(text);

        Assert.That(result, Is.EqualTo(expected));
    }

    [Test]
    [TestCase("abandonat", "abandonat")]
    [TestCase("actualizat", "actualizat")]
    [TestCase("adanc", "adânc")]
    [TestCase("ajutat", "ajutat")]
    [TestCase("aliniat", "aliniat")]
    [TestCase("amanat", "amânat")]
    [TestCase("aprins", "aprins")]
    [TestCase("ars", "ars")]
    [TestCase("ascultat", "ascultat")]
    [TestCase("ascultator", "ascultător")]
    [TestCase("ascuns", "ascuns")]
    [TestCase("avut", "avut")]
    [TestCase("bogat", "bogat")]
    [TestCase("castigator", "câștigător")]
    [TestCase("cersetor", "cerșetor")]
    [TestCase("cires", "cireș")]
    [TestCase("comunist", "comunist")]
    [TestCase("confirmat", "confirmat")]
    [TestCase("crescut", "crescut")]
    [TestCase("cunoscut", "cunoscut")]
    [TestCase("delegat", "delegat")]
    [TestCase("democrat", "democrat")]
    [TestCase("depasit", "depășit")]
    [TestCase("dependent", "dependent")]
    [TestCase("deschis", "deschis")]
    [TestCase("desprins", "desprins")]
    [TestCase("dormit", "dormit")]
    [TestCase("dusman", "dușman")]
    [TestCase("enorias", "enoriaș")]
    [TestCase("estimat", "estimat")]
    [TestCase("facut", "făcut")]
    [TestCase("fascist", "fascist")]
    [TestCase("ferit", "ferit")]
    [TestCase("fiert", "fiert")]
    [TestCase("functional", "funcțional")]
    [TestCase("gasit", "găsit")]
    [TestCase("imprumutat", "împrumutat")]
    [TestCase("imprumutat", "împrumutat")]
    [TestCase("incaltat", "încălțat")]
    [TestCase("inchis", "închis")]
    [TestCase("inculpat", "inculpat")]
    [TestCase("intampinat", "întâmpinat")]
    [TestCase("intarziat", "întârziat")]
    [TestCase("interesat", "interesat")]
    [TestCase("intreg", "întreg")]
    [TestCase("jucator", "jucător")]
    [TestCase("judecator", "judecător")]
    [TestCase("linistit", "liniștit")]
    [TestCase("lucrator", "lucrător")]
    [TestCase("luptator", "luptător")]
    [TestCase("mancat", "mâncat")]
    [TestCase("meserias", "meseriaș")]
    [TestCase("mort", "mort")]
    [TestCase("nationalist", "naționalist")]
    [TestCase("nazist", "nazist")]
    [TestCase("omorat", "omorât")]
    [TestCase("onorat", "onorat")]
    [TestCase("operat", "operat")]
    [TestCase("pacatos", "păcătos")]
    [TestCase("pirat", "pirat")]
    [TestCase("politist", "polițist")]
    [TestCase("postas", "poștaș")]
    [TestCase("preferat", "preferat")]
    [TestCase("preot", "preot")]
    [TestCase("prost", "prost")]
    [TestCase("razboinic", "războinic")]
    [TestCase("roscat", "roșcat")]
    [TestCase("sarac", "sărac")]
    [TestCase("sef", "șef")]
    [TestCase("sobolan", "șobolan")]
    [TestCase("soldat", "soldat")]
    [TestCase("stins", "stins")]
    [TestCase("talhar", "tâlhar")]
    [TestCase("tampit", "tâmpit")]
    [TestCase("tamplar", "tâmplar")]
    [TestCase("taran", "țăran")]
    [TestCase("terminat", "terminat")]
    [TestCase("trantit", "trântit")]
    [TestCase("turist", "turist")]
    [TestCase("ucis", "ucis")]
    [TestCase("urmator", "următor")]
    [TestCase("urs", "urs")]
    [TestCase("vames", "vameș")]
    [TestCase("vanzator", "vânzător")]
    [TestCase("varsator", "vărsător")]
    [TestCase("vinovat", "vinovat")]
    [TestCase("vizat", "vizat")]
    [TestCase("vizitat", "vizitat")]
    [TestCase("vrut", "vrut")]
    public void GivenMasculineAdjectiveOrNoun_WhenApplyingTheRule_ThenAllVariationsAreAsExpected(
        string originalNoun,
        string expectedNoun)
    {
        string[] suffixes = ["", "i", "ii", "ilor", "ul", "ului"];
        IGrammarRule rule = CreateRule("NuciText.Grammar.Romanian.Rules.RomanianDiacriticsRule");

        foreach (string suffix in suffixes)
        {
            string result = rule.Apply(originalNoun + suffix);

            if (suffix.StartsWith("i", StringComparison.Ordinal))
            {
                if (originalNoun.EndsWith("st", StringComparison.Ordinal) &&
                    expectedNoun.EndsWith("st", StringComparison.Ordinal))
                {
                    expectedNoun = expectedNoun[..^2] + "șt";
                }
                else if (originalNoun.EndsWith("t", StringComparison.Ordinal) &&
                         expectedNoun.EndsWith("t", StringComparison.Ordinal))
                {
                    expectedNoun = expectedNoun[..^1] + "ț";
                }
                else if (originalNoun.EndsWith("s", StringComparison.Ordinal) &&
                         expectedNoun.EndsWith("s", StringComparison.Ordinal))
                {
                    expectedNoun = expectedNoun[..^1] + "ș";
                }
            }

            Assert.That(result, Is.EqualTo(expectedNoun + suffix));
        }
    }

    [Test]
    [TestCase("comanda")]
    [TestCase("consuma")]
    [TestCase("costa")]
    [TestCase("doua")]
    [TestCase("garda")]
    [TestCase("mutam")]
    [TestCase("necesitam")]
    [TestCase("palma")]
    [TestCase("pita")]
    [TestCase("scoala")]
    [TestCase("stima")]
    [TestCase("strada")]
    [TestCase("strigat")]
    [TestCase("suta")]
    [TestCase("terminam")]
    [TestCase("tipa")]
    [TestCase("tipi")]
    [TestCase("urma")]
    [TestCase("vina")]
    public void GivenDiacriticlessWord_WhenThereIsAmbiguity_ThenDiacriticsAreNotAdded(string text)
    {
        IGrammarRule rule = CreateRule("NuciText.Grammar.Romanian.Rules.RomanianDiacriticsRule");

        string result = rule.Apply(text);

        Assert.That(result, Is.EqualTo(text));
    }

    static IGrammarRule CreateRule(string typeName)
    {
        Type ruleType = typeof(RomanianGrammarCorrector).Assembly.GetType(typeName, throwOnError: true)!;
        return (IGrammarRule)Activator.CreateInstance(ruleType, nonPublic: true)!;
    }
}