using System;
using System.Collections.Generic;
using NUnit.Framework;

namespace NuciText.Grammar.Romanian.UnitTests.Rules;

[TestFixture]
public class RomanianDiacriticsRuleTests
{
    [TestCase("actualizeaza", "actualizează")]
    [TestCase("adoarma", "adoarmă")]
    [TestCase("ajuti", "ajuți")]
    [TestCase("aliniaza", "aliniază")]
    [TestCase("amanam", "amânam")]
    [TestCase("apartine", "aparține")]
    [TestCase("aprinda", "aprindă")]
    [TestCase("aprinsi", "aprinși")]
    [TestCase("as prefera", "aș prefera")]
    [TestCase("asa", "așa")]
    [TestCase("ascunsa", "ascunsă")]
    [TestCase("balanta", "balanța")]
    [TestCase("barcuta", "bărcuța")]
    [TestCase("bosi", "boși")]
    [TestCase("bosii", "boșii")]
    [TestCase("bosilor", "boșilor")]
    [TestCase("ca am", "că am")]
    [TestCase("ca imi", "că îmi")]
    [TestCase("cacat", "câcat")]
    [TestCase("caine", "câine")]
    [TestCase("castigam", "câștigam")]
    [TestCase("castigat", "câștigat")]
    [TestCase("catel", "cățel")]
    [TestCase("cateva", "câteva")]
    [TestCase("cateva", "câteva")]
    [TestCase("cirese", "cireșe")]
    [TestCase("citeasca", "citească")]
    [TestCase("cladire", "clădire")]
    [TestCase("completeaza", "completează")]
    [TestCase("concentreaza", "concentrează")]
    [TestCase("consideratie", "considerație")]
    [TestCase("corecteaza", "corectează")]
    [TestCase("cresti", "crești")]
    [TestCase("cunoastere", "cunoaștere")]
    [TestCase("daca", "dacă")]
    [TestCase("defileaza", "defilează")]
    [TestCase("definite", "definiție")]
    [TestCase("democratia", "democrația")]
    [TestCase("dependinta", "dependința")]
    [TestCase("deschisa", "deschisă")]
    [TestCase("distributie", "distribuție")]
    [TestCase("esti", "ești")]
    [TestCase("estimeaza", "estimează")]
    [TestCase("facea", "făcea")]
    [TestCase("faceam", "făceam")]
    [TestCase("faceti", "faceți")]
    [TestCase("fereasca", "ferească")]
    [TestCase("fleosc", "fleoșc")]
    [TestCase("fondata", "fondată")]
    [TestCase("frisca", "frișca")]
    [TestCase("functionala", "funcțională")]
    [TestCase("functioneaza,", "funcționează,")]
    [TestCase("functioneaza", "funcționează")]
    [TestCase("furnicutele", "furnicutele")]
    [TestCase("garzii", "gărzii")]
    [TestCase("gasesc", "găsesc")]
    [TestCase("gradinita", "grădinița")]
    [TestCase("greseasca", "gresească")]
    [TestCase("greselile", "greșelile")]
    [TestCase("hranesc", "hrănesc")]
    [TestCase("impartit", "împărțit")]
    [TestCase("impreuna", "împreună")]
    [TestCase("imprumut", "împrumut")]
    [TestCase("incearca", "încearcă")]
    [TestCase("incepem", "începem")]
    [TestCase("ingrijorare", "îngrijorare")]
    [TestCase("inlocuiasca", "înlocuiască")]
    [TestCase("inot", "înot")]
    [TestCase("inseamna", "înseamnă")]
    [TestCase("intoarce", "întoarce")]
    [TestCase("intreaga", "întreaga")]
    [TestCase("iteratia", "iterația")]
    [TestCase("iuti", "iuți")]
    [TestCase("jucatoarele", "jucătorarele")]
    [TestCase("libertatii", "libertății")]
    [TestCase("logheaza", "loghează")]
    [TestCase("mananc", "mănânc")]
    [TestCase("mancare", "mâncare")]
    [TestCase("mentenanta", "mentenanța")]
    [TestCase("mentin", "mențin")]
    [TestCase("mineaza", "minează")]
    [TestCase("minereasca", "minerească")]
    [TestCase("munceasca", "muncească")]
    [TestCase("muntii", "munții")]
    [TestCase("muti", "muți")]
    [TestCase("nationale", "naționale")]
    [TestCase("natiune", "națiune")]
    [TestCase("niste", "niște")]
    [TestCase("nivelata", "nivelată")]
    [TestCase("noastra", "noastră")]
    [TestCase("noptii", "nopții")]
    [TestCase("noștri", "noștri")]
    [TestCase("odata", "odată")]
    [TestCase("odihneasca", "odihnească")]
    [TestCase("odinioara", "odinioară")]
    [TestCase("orasel", "orășel")]
    [TestCase("orasele", "orașele")]
    [TestCase("oraselele", "orășelele")]
    [TestCase("orasu", "orașu")]
    [TestCase("oua", "ouă")]
    [TestCase("pacat", "păcat")]
    [TestCase("pacate", "păcate")]
    [TestCase("pacatosule", "păcătosule")]
    [TestCase("palmuit", "pălmuit")]
    [TestCase("pamant", "pământ")]
    [TestCase("pamantean", "pământean")]
    [TestCase("parea", "părea")]
    [TestCase("parerea", "părerea")]
    [TestCase("piata", "piața")]
    [TestCase("placere", "plăcere")]
    [TestCase("planuiesti", "plănuiești")]
    [TestCase("planuit", "plănuit")]
    [TestCase("poti sa", "poți să")]
    [TestCase("poti", "poți")]
    [TestCase("prefera sa", "prefera să")]
    [TestCase("pregatit", "pregătit")]
    [TestCase("primarie", "primărie")]
    [TestCase("puna", "pună")]
    [TestCase("pusca", "pușca")]
    [TestCase("rabdare", "răbdare")]
    [TestCase("raman", "rămân")]
    [TestCase("ramas", "rămas")]
    [TestCase("raspunsului", "răspunsului")]
    [TestCase("recunoasca", "recunoască")]
    [TestCase("reductie", "reducție")]
    [TestCase("renuntam", "renunțăm")]
    [TestCase("reusim", "reușim")]
    [TestCase("ridicata", "ridicată")]
    [TestCase("roscata", "roșcata")]
    [TestCase("rugaciune", "rugăciune")]
    [TestCase("ruleaza", "rulează")]
    [TestCase("sambata", "sâmbăta")]
    [TestCase("sansa", "șansa")]
    [TestCase("saptamana", "săptămâna")]
    [TestCase("saraca", "săraca")]
    [TestCase("saracii", "săracii")]
    [TestCase("saracilor", "săracilor")]
    [TestCase("saracit", "săracit")]
    [TestCase("sarat", "sărat")]
    [TestCase("sarbatoare", "sărbătoare")]
    [TestCase("sarit", "sărit")]
    [TestCase("sarpe", "șarpe")]
    [TestCase("scoasa", "scoasă")]
    [TestCase("scobeste", "scobește")]
    [TestCase("scolile", "școlile")]
    [TestCase("scuzati", "scuzați")]
    [TestCase("semneaza", "semnează")]
    [TestCase("serupit", "șerpuit")]
    [TestCase("sfarseasca", "sfârșească")]
    [TestCase("sfinteasca", "sfințească")]
    [TestCase("slefuit", "șlefuit")]
    [TestCase("slefuita", "șlefuita")]
    [TestCase("spalat", "spălat")]
    [TestCase("sparga", "spargă")]
    [TestCase("spatiu", "spațiu")]
    [TestCase("stanga", "stânga")]
    [TestCase("starneste", "stârnește")]
    [TestCase("stiu", "știu")]
    [TestCase("stramt", "strâmt")]
    [TestCase("stropeasca", "stropească")]
    [TestCase("susta", "șusta")]
    [TestCase("taieri", "tăieri")]
    [TestCase("tarnacop", "târnăcop")]
    [TestCase("teava", "țeava")]
    [TestCase("teleporteaza", "teleportează")]
    [TestCase("temnita", "temnița")]
    [TestCase("temnite", "temnițe")]
    [TestCase("tipai", "țipai")]
    [TestCase("tipam", "țipam")]
    [TestCase("tipat", "țipat")]
    [TestCase("totii", "toții")]
    [TestCase("totusi", "totuși")]
    [TestCase("trantesc", "trântesc")]
    [TestCase("trânteasca", "trântească")]
    [TestCase("urmaresc", "urmăresc")]
    [TestCase("vamala", "vamală")]
    [TestCase("veniti", "veniți")]
    [TestCase("viata", "viața")]
    [TestCase("vietii", "vieții")]
    [TestCase("voiasca", "voiască")]
    [TestCase("voiati", "voiați")]
    [TestCase("vopseasca", "vopsească")]
    [TestCase("vorbeasca", "vorbească")]
    [TestCase("voteaza", "votează")]
    [TestCase("voua", "vouă")]
    [TestCase("vreti", "vreți")]
    public void Apply_AddsExpectedDiacritics(string text, string expected)
    {
        IGrammarRule rule = CreateRule("NuciText.Grammar.Romanian.Rules.RomanianDiacriticsRule");

        string result = rule.Apply(text);

        Assert.That(result, Is.EqualTo(expected));
    }

    [Test]
    [TestCase("abandonat", "abandonat")]
    [TestCase("achizitionat", "achiziționat")]
    [TestCase("actualizat", "actualizat")]
    [TestCase("adanc", "adânc")]
    [TestCase("adus", "adus")]
    [TestCase("adusi", "aduși")]
    [TestCase("agent", "agent")]
    [TestCase("aiurist", "aiurist")]
    [TestCase("ajutat", "ajutat")]
    [TestCase("ales", "ales")]
    [TestCase("alimentat", "alimentat")]
    [TestCase("aliniat", "aliniat")]
    [TestCase("alocat", "alocat")]
    [TestCase("amanat", "amânat")]
    [TestCase("aparut", "apărut")]
    [TestCase("aprins", "aprins")]
    [TestCase("apropriat", "apropriat")]
    [TestCase("ars", "ars")]
    [TestCase("aruncat", "aruncat")]
    [TestCase("ascultat", "ascultat")]
    [TestCase("ascultator", "ascultător")]
    [TestCase("ascuns", "ascuns")]
    [TestCase("aspirat", "aspirat")]
    [TestCase("astupat", "astupat")]
    [TestCase("atentionat", "atenționat")]
    [TestCase("aurist", "aurist")]
    [TestCase("avertizat", "avertizat")]
    [TestCase("avocat", "avocat")]
    [TestCase("avut", "avut")]
    [TestCase("binecuvantat", "binecuvântat")]
    [TestCase("bogat", "bogat")]
    [TestCase("bot", "bot")]
    [TestCase("bucatar", "bucătar")]
    [TestCase("calcat", "călcat")]
    [TestCase("caldut", "călduț")]
    [TestCase("capitan", "căpitan")]
    [TestCase("castigator", "câștigător")]
    [TestCase("centrist", "centrist")]
    [TestCase("cersetor", "cerșetor")]
    [TestCase("cires", "cireș")]
    [TestCase("ciupitist", "ciupitist")]
    [TestCase("comandant", "comandant")]
    [TestCase("comandat", "comandat")]
    [TestCase("comunist", "comunist")]
    [TestCase("confirmat", "confirmat")]
    [TestCase("constructor", "constructor")]
    [TestCase("construit", "construit")]
    [TestCase("craftat", "craftat")]
    [TestCase("credincios", "credincios")]
    [TestCase("crescut", "crescut")]
    [TestCase("crestin", "creștin")]
    [TestCase("cules", "cules")]
    [TestCase("cumparat", "cumpărat")]
    [TestCase("cunoscut", "cunoscut")]
    [TestCase("curat", "curat")]
    [TestCase("cutitar", "cuțitar")]
    [TestCase("delegat", "delegat")]
    [TestCase("democrat", "democrat")]
    [TestCase("departat", "depărtat")]
    [TestCase("depasit", "depășit")]
    [TestCase("dependent", "dependent")]
    [TestCase("depozitat", "depozitat")]
    [TestCase("descarcat", "descărcat")]
    [TestCase("deschis", "deschis")]
    [TestCase("descoperit", "descoperit")]
    [TestCase("desprins", "desprins")]
    [TestCase("dichisit", "dichisit")]
    [TestCase("diparut", "dispărut")]
    [TestCase("doborat", "doborât")]
    [TestCase("dormit", "dormit")]
    [TestCase("dragut", "drăguț")]
    [TestCase("dusman", "dușman")]
    [TestCase("enorias", "enoriaș")]
    [TestCase("estimat", "estimat")]
    [TestCase("excavat", "excavat")]
    [TestCase("expirat", "expirat")]
    [TestCase("facut", "făcut")]
    [TestCase("familist", "familist")]
    [TestCase("fascist", "fascist")]
    [TestCase("ferit", "ferit")]
    [TestCase("fiert", "fiert")]
    [TestCase("frant", "frânt")]
    [TestCase("functional", "funcțional")]
    [TestCase("gasit", "găsit")]
    [TestCase("georgist", "georgist")]
    [TestCase("hranit", "hrănit")]
    [TestCase("iesit", "ieșit")]
    [TestCase("imparat", "împărat")]
    [TestCase("imprumutat", "împrumutat")]
    [TestCase("impuscat", "împușcat")]
    [TestCase("imputit", "împuțit")]
    [TestCase("incaltat", "încălțat")]
    [TestCase("incalzit", "încălzit")]
    [TestCase("incarcat", "încărcat")]
    [TestCase("inchis", "închis")]
    [TestCase("inculpat", "inculpat")]
    [TestCase("indepartat", "îndepărtat")]
    [TestCase("inghtat", "înghețat")]
    [TestCase("inmultit", "înmulțit")]
    [TestCase("inspirat", "inspirat")]
    [TestCase("intampinat", "întâmpinat")]
    [TestCase("intarziat", "întârziat")]
    [TestCase("interesat", "interesat")]
    [TestCase("intrat", "intrat")]
    [TestCase("intreg", "întreg")]
    [TestCase("jucat", "jucat")]
    [TestCase("jucator", "jucător")]
    [TestCase("judecator", "judecător")]
    [TestCase("lasat", "lăsat")]
    [TestCase("linistit", "liniștit")]
    [TestCase("locotenent", "locotenent")]
    [TestCase("lucrator", "lucrător")]
    [TestCase("luptator", "luptător")]
    [TestCase("mancat", "mâncat")]
    [TestCase("maresal", "mareșal")]
    [TestCase("masurat", "măsurat")]
    [TestCase("meserias", "meseriaș")]
    [TestCase("minerit", "minerit")]
    [TestCase("moderat", "moderat")]
    [TestCase("modificat", "modificat")]
    [TestCase("mort", "mort")]
    [TestCase("muist", "muist")]
    [TestCase("muncit", "muncit")]
    [TestCase("nationalist", "naționalist")]
    [TestCase("nazist", "nazist")]
    [TestCase("necredincios", "necredincios")]
    [TestCase("nesimtit", "nesimțit")]
    [TestCase("nihilist", "nihilist")]
    [TestCase("numarat", "numărat")]
    [TestCase("obosit", "obosit")]
    [TestCase("observat", "observat")]
    [TestCase("odihnit", "odihnit")]
    [TestCase("omorat", "omorât")]
    [TestCase("onorat", "onorat")]
    [TestCase("operat", "operat")]
    [TestCase("oxidat", "oxidat")]
    [TestCase("pacatos", "păcătos")]
    [TestCase("perfect", "perfect")]
    [TestCase("pierdut", "pierdut")]
    [TestCase("pilot", "pilot")]
    [TestCase("pirat", "pirat")]
    [TestCase("pivot", "pivot")]
    [TestCase("plantat", "plantat")]
    [TestCase("politist", "polițist")]
    [TestCase("postas", "poștaș")]
    [TestCase("prefect", "prefect")]
    [TestCase("preferat", "preferat")]
    [TestCase("preot", "preot")]
    [TestCase("prins", "prinși")]
    [TestCase("progresist", "progresist")]
    [TestCase("prost", "prost")]
    [TestCase("purist", "purist")]
    [TestCase("puscat", "pușcat")]
    [TestCase("raposat", "răposat")]
    [TestCase("razboinic", "războinic")]
    [TestCase("roscat", "roșcat")]
    [TestCase("salvat", "salvat")]
    [TestCase("sapat", "săpat")]
    [TestCase("sarac", "sărac")]
    [TestCase("savant", "savant")]
    [TestCase("sef", "șef")]
    [TestCase("semanat", "semănat")]
    [TestCase("simtit", "simțit")]
    [TestCase("sinucis", "sinucis")]
    [TestCase("sobolan", "șobolan")]
    [TestCase("socialist", "socialist")]
    [TestCase("sofer", "șofer")]
    [TestCase("soldat", "soldat")]
    [TestCase("sorosist", "soroșist")]
    [TestCase("spanzurat", "spânzurat")]
    [TestCase("spectaculos", "spectaculos")]
    [TestCase("speriat", "speriat")]
    [TestCase("staret", "stareț")]
    [TestCase("stins", "stins")]
    [TestCase("surprins", "surprins")]
    [TestCase("talhar", "tâlhar")]
    [TestCase("tampit", "tâmpit")]
    [TestCase("tamplar", "tâmplar")]
    [TestCase("tanchist", "tanchist")]
    [TestCase("taran", "țăran")]
    [TestCase("terminat", "terminat")]
    [TestCase("trantit", "trântit")]
    [TestCase("trecut", "trecut")]
    [TestCase("trimis", "trimis")]
    [TestCase("turist", "turist")]
    [TestCase("ucis", "ucis")]
    [TestCase("umplut", "umplut")]
    [TestCase("urmator", "următor")]
    [TestCase("urs", "urs")]
    [TestCase("validat", "validat")]
    [TestCase("vames", "vameș")]
    [TestCase("vandut", "vândut")]
    [TestCase("vanzator", "vânzător")]
    [TestCase("varsat", "vărsat")]
    [TestCase("varsator", "vărsător")]
    [TestCase("vazut", "văzut")]
    [TestCase("vinovat", "vinovat")]
    [TestCase("visator", "visător")]
    [TestCase("vizat", "vizat")]
    [TestCase("vizitat", "vizitat")]
    [TestCase("vrut", "vrut")]
    public void GivenMasculineAdjectiveOrNoun_WhenApplyingTheRule_ThenAllVariationsAreAsExpected(
        string originalNoun2,
        string expectedNoun)
    {
        string[] suffixes = ["", "i", "ii", "ilor", "ul", "ului"];
        IGrammarRule rule = CreateRule("NuciText.Grammar.Romanian.Rules.RomanianDiacriticsRule");

        List<string> inputNouns = [originalNoun2];

        for (int i = 0; i < expectedNoun.Length; i++)
        {
            break;
            char c = expectedNoun[i];

            if (c == 'ă' || c == 'â')
            {
                inputNouns.Add(expectedNoun[..i] + expectedNoun[i] + expectedNoun[(i + 1)..]);
                inputNouns.Add(expectedNoun[..i] + 'a' + expectedNoun[(i + 1)..]);
            }
            if (c == 'î')
            {
                inputNouns.Add(expectedNoun[..i] + expectedNoun[i] + expectedNoun[(i + 1)..]);
                inputNouns.Add(expectedNoun[..i] + 'i' + expectedNoun[(i + 1)..]);
            }
            if (c == 'ș')
            {
                inputNouns.Add(expectedNoun[..i] + expectedNoun[i] + expectedNoun[(i + 1)..]);
                inputNouns.Add(expectedNoun[..i] + 's' + expectedNoun[(i + 1)..]);
            }
            if (c == 'ț')
            {
                inputNouns.Add(expectedNoun[..i] + expectedNoun[i] + expectedNoun[(i + 1)..]);
                inputNouns.Add(expectedNoun[..i] + 't' + expectedNoun[(i + 1)..]);
            }
        }

        foreach (string originalNoun in inputNouns)
        {
            foreach (string suffix in suffixes)
            {
                string result = rule.Apply(originalNoun + suffix);

                if (suffix.StartsWith("i", StringComparison.Ordinal))
                {
                    if (originalNoun.EndsWith("st", StringComparison.Ordinal) &&
                        expectedNoun.EndsWith("st", StringComparison.Ordinal))
                    {
                        expectedNoun = expectedNoun[..^2] + "șt";
                    }
                    else if (originalNoun.EndsWith("t", StringComparison.Ordinal) &&
                            expectedNoun.EndsWith("t", StringComparison.Ordinal))
                    {
                        expectedNoun = expectedNoun[..^1] + "ț";
                    }
                    else if (originalNoun.EndsWith("s", StringComparison.Ordinal) &&
                            expectedNoun.EndsWith("s", StringComparison.Ordinal))
                    {
                        expectedNoun = expectedNoun[..^1] + "ș";
                    }
                }

                Assert.That(result, Is.EqualTo(expectedNoun + suffix));
            }
        }
    }

    [Test]
    [TestCase("aparat")]
    [TestCase("comanda")]
    [TestCase("consuma")]
    [TestCase("costa")]
    [TestCase("doua")]
    [TestCase("garda")]
    [TestCase("mutam")]
    [TestCase("necesitam")]
    [TestCase("palma")]
    [TestCase("pita")]
    [TestCase("scoala")]
    [TestCase("stima")]
    [TestCase("strada")]
    [TestCase("strigat")]
    [TestCase("suta")]
    [TestCase("terminam")]
    [TestCase("tipa")]
    [TestCase("tipi")]
    [TestCase("urma")]
    [TestCase("vina")]
    public void GivenDiacriticlessWord_WhenThereIsAmbiguity_ThenDiacriticsAreNotAdded(string text)
    {
        IGrammarRule rule = CreateRule("NuciText.Grammar.Romanian.Rules.RomanianDiacriticsRule");

        string result = rule.Apply(text);

        Assert.That(result, Is.EqualTo(text));
    }

    static IGrammarRule CreateRule(string typeName)
    {
        Type ruleType = typeof(RomanianGrammarCorrector).Assembly.GetType(typeName, throwOnError: true)!;
        return (IGrammarRule)Activator.CreateInstance(ruleType, nonPublic: true)!;
    }
}